title: Mingzhen Tian
url: "https://mingzhentian.github.io/"
#baseurl: "/researcher/"

markdown: kramdown
#ins_logo: "./班徽（白底）.jpg"

tracking_id: #

footer: yes

footer_text: "Page design by MingzhenTian"

sass:
    style: compressed
    sass_dir: _sass

nav:
 - name: "About"
   link: "researcher"
 - name: "Contact"
   link: "contact"
 - name: "Resume"
   link: "resume.pdf"
 - name: "中文"
   link: "/researcher/Chinese/"
