title: Mingzhen Tian
url: "https://mingzhentian.github.io/"
baseurl: "/cv/"

markdown: kramdown
#ins_logo: "./班徽（白底）.jpg"

tracking_id: #

footer: yes

footer_text: "Page design by MingzhenTian"

sass:
    style: compressed
    sass_dir: _sass

nav:
 - name: "About"
   link: "{{ https://mingzhentian.github.io/cv/ }}/index"
 - name: "Contact"
   link: "{{ https://mingzhentian.github.io/cv/ }}/contact"
 - name: "Resume"
   link: "resume.pdf"
 - name: "中文"
   link: "{{ https://mingzhentian.github.io/cv/ }}/chinese"
